using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System.Diagnostics;
using System.Reflection;
using FunkyMock;
using FunkyMock.External;
using Xunit;

namespace FunkyMockTests;

[Collection("AllowTesting-IndentedStringBuilder.NewLine")]
public class Debuggable
{
    [Fact]
    public void SimpleGeneratorTest()
    {
        var eol = IndentedStringBuilder.NewLine;
        try
        {
            // this file is LF (not CRLF) so we need to "normalise" the line ending
            IndentedStringBuilder.NewLine = "\n";
            Compilation inputCompilation = CreateCompilation(@"
namespace Root.MyCode {
    using System;
    public class AnyType {
        public string Word {get;set;}
    }

    public interface IThing {
        string Text(int number);
        bool Predicate(float f, AnyType anyType);
        DateTime ReadOnly {get;}
        int ReadWrite {get;set;}
        bool WriteOnly {set;}
    }
}
namespace OtherRoot.Testing {
    using Root.MyCode;

    [Funky(typeof(IThing))]
    public partial class AnyMocker {
        // Will match 'GeneratedSource'
    }
}
public static class App{public static void Main(){}}
");

            // directly create an instance of the generator
            // (Note: in the compiler this is loaded from an assembly, and created via reflection at runtime)
            var generator = new FunkyGenerator();

            // Create the driver that will control the generation, passing in our generator
            GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

            // Run the generation pass
            // (Note: the generator driver itself is immutable, and all calls return an updated version of the driver that you should use for subsequent calls)
            driver = driver.RunGeneratorsAndUpdateCompilation(inputCompilation, out var outputCompilation,
                out var diagnostics);

            // We can now assert things about the resulting compilation:
            Debug.Assert(diagnostics.IsEmpty); // there were no diagnostics created by the generators
            Debug.Assert(outputCompilation.SyntaxTrees.Count() ==
                         3); // we have three syntax trees, the original 'user' provided one, our fixed 'Funky' attribute and the one added by the generator
            // Debug.Assert(outputCompilation.GetDiagnostics().IsEmpty); // verify the compilation with the added source has no diagnostics
            //
            // // Or we can look at the results directly:
            GeneratorDriverRunResult runResult = driver.GetRunResult();
            //
            // // The runResult contains the combined results of all generators passed to the driver
            // Debug.Assert(runResult.GeneratedTrees.Length == 1);
            // Debug.Assert(runResult.Diagnostics.IsEmpty);
            //
            // // Or you can access the individual results on a by-generator basis
            GeneratorRunResult generatorResult = runResult.Results[0];
            // // Debug.Assert(generatorResult.Generator == generator);
            // Debug.Assert(generatorResult.Diagnostics.IsEmpty);
            Debug.Assert(generatorResult.GeneratedSources.Length == 2);
            var source = generatorResult.GeneratedSources[1].SourceText.ToString();

            Assert.Equal(GeneratedSource, source);
            // Debug.Assert(generatorResult.Exception is null);
        }
        finally
        {
            IndentedStringBuilder.NewLine = eol;
        }
    }

    private static Compilation CreateCompilation(string source)
        => CSharpCompilation.Create("compilation",
            new[] { CSharpSyntaxTree.ParseText(source) },
            new[] { MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location) },
            new CSharpCompilationOptions(OutputKind.ConsoleApplication));

    private const string GeneratedSource = """
// <auto-generated/>
#nullable enable
namespace OtherRoot.Testing;

// Standard global using
using global::System;
using global::System.Collections.Generic;
using global::System.IO;
using global::System.Linq;
using global::System.Net.Http;
using global::System.Threading;
using global::System.Threading.Tasks;

public partial class AnyMocker : Root.MyCode.IThing
{
    public Func<int, string>? OnText;
    public Func<float, Root.MyCode.AnyType, bool>? OnPredicate;
    public Func<System.DateTime>? OnGetReadOnly;
    public Func<int>? OnGetReadWrite;
    public Action<int>? OnSetReadWrite;
    public Action<bool>? OnSetWriteOnly;

    public string Text(int number) {
        if (OnText is null) { throw new System.NotImplementedException("'OnText' has not been assigned"); }
        return OnText(number);
    }
    public bool Predicate(float f, Root.MyCode.AnyType anyType) {
        if (OnPredicate is null) { throw new System.NotImplementedException("'OnPredicate' has not been assigned"); }
        return OnPredicate(f, anyType);
    }
    public System.DateTime ReadOnly {
        get {
            if (OnGetReadOnly is null) { throw new System.NotImplementedException("'OnGetReadOnly' has not been assigned"); }
            return OnGetReadOnly();
        }
    }
    public int ReadWrite {
        get {
            if (OnGetReadWrite is null) { throw new System.NotImplementedException("'OnGetReadWrite' has not been assigned"); }
            return OnGetReadWrite();
        }
        set {
            if (OnSetReadWrite is null) { throw new System.NotImplementedException("'OnSetReadWrite' has not been assigned"); }
            OnSetReadWrite(value);
        }
    }
    public bool WriteOnly {
        set {
            if (OnSetWriteOnly is null) { throw new System.NotImplementedException("'OnSetWriteOnly' has not been assigned"); }
            OnSetWriteOnly(value);
        }
    }
}

""";
}
