namespace FunkyMock;

internal sealed class StaticSource {
    private static readonly string FunkyNamespaceName = "FunkyMock";
    internal static readonly string FunkyNamespaceShortName = "Funky";
    internal static readonly string FunkyNamespaceLongName = $"{FunkyNamespaceShortName}Attribute";
    internal static readonly string FunkyAttributeFullname = $"{FunkyNamespaceName}.{FunkyNamespaceLongName}";

    private static readonly string GeneratedCodeAttribute =
        $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute("+
        $@"""{typeof(StaticSource).Assembly.GetName().Name}"", "+
        $@"""{typeof(StaticSource).Assembly.GetName().Version}"""+
        $@")]";

    internal static readonly string FunkyMockAttributeSource = $@"// <auto-generated/>
#nullable enable
namespace {FunkyNamespaceName};
{GeneratedCodeAttribute}
[global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class {FunkyNamespaceLongName} : global::System.Attribute {{ }}
";
}
