name: CI

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'funky.sln'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        id: build-version
        env:
          PRERELEASE: ${{ github.event.release.prerelease }}
        run: |
          BUILD_VERSION=$(./build/build_version.sh $GITHUB_REF_NAME $PRERELEASE)
          echo "BUILD_VERSION=$BUILD_VERSION">> $GITHUB_OUTPUT

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build
        env:
          BUILD_VERSION: ${{ steps.build-version.outputs.BUILD_VERSION }}
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
